language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip3 install coverage
# command to run tests
script:
  - python3 -m unittest
after_success:
  - coverage run test_rpn.py
  - coverage report
